### PR TITLE
Improved locking performance on .NET 9.0+

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
The new System.Threading.Lock offers greater performance, as independent benchmarks show (eg https://steven-giesel.com/blogPost/4cf6d48a-ec9d-4c68-961c-31fd8d8c1340)

### CODE REVIEW

**Comment by witskeeper** [comment]
It looks like the CI is broken.

@MarkCiliaVincenti can you fix the CI error？

error CA2252: '_lock''s type contains the preview type 'Lock' and requires opting into preview features. See https://aka.ms/dotnet-warnings/preview-features for more information. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2252)

**Comment by MarkCiliaVincenti** [comment]
Interesting. This is happening because it's running under 9.0.100-preview.4.24267.66 instead of the latest (preview 7). I made a hopeful fix but given the workflow needs manual approval a trial-and-error approach is going to be tricky.

**Comment by MarkCiliaVincenti** [comment]
@witskeeper

**Comment by witskeeper** [comment]
The approved workflow has been modified and should be able to run automatically now.

**Comment by witskeeper** [comment]
i will try to update  sdk to preview 7

**Comment by MarkCiliaVincenti** [comment]
But now the error is different. It is running on preview 7

The message timed out in the backlog attempting to send because no connection became available (5000ms)

**Comment by witskeeper** [comment]
I improved the dependencies and test cases related to .NET 9 and specified using preview 7
It might work.

**Review by witskeeper — APPROVED** [review]
Done

**Comment by witskeeper** [comment]
Thank you for your contribution. @MarkCiliaVincenti

**Pull request merged**
